### ISSUE TITLE
[CW-2854] feature:  Ability to limit open conversations per agent

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#1198]
The number of open conversations an agent can handle is limited. So how can we consider this case in a round-robin assignment? 

---- 
### Phase 1

- [x] In the inbox settings for auto-assignment, Introduce an option for a max limit of conversations that an agent can handle in that inbox.
- [x] The auto-assignment logic will respect this setting during execution
  - [x] if the number of open tickets for the chosen agent has reached or passed the max limit
  - [x] auto-assignment will differ the ticket to the next agent in the queue [ until the system finds an agent that hasn't passed the max limit ] 
  - [x] if all agents have passed their maximum limit, the conversation is left unassigned. 

### Phase 2

- [ ] Introduce a setting for an agent to limit the maximum conversations they can handle. 
- [ ] In the case of auto-assignment, the agent limit takes precedence over the auto-assignment limit
- [ ] When the ticket is assigned via UI and the agent is working at the maximum capacity show an error stating the agent is working at full capacity. 

<sub>[CW-2854](https://linear.app/chatwoot/issue/CW-2854/feature-ability-to-limit-open-conversations-per-agent)</sub>

**Comment by AlessandraFrancez** [comment]
Thanks for opening this, some food for thought:

- It could be 2 types of limit: 
A soft limit that applies to round robin assignment
A hard limit that prevents agents to assigning more than X conversations to themselves

- Looking at competitors' approaches, Zendesk for example also has a "personal limit" that agents can set

**Comment by pranavrajs** [comment]
@sojan-official @tejaswinichile Please evaluate the effort required for Phase 1 as per the described spec. Let us prioritize this in the next sprint.

Note: This is only required for auto-assignment cases. In this iteration, we will not consider the case when an admin or another agent manually assigns a conversation to an agent.

**Comment by sojan-official** [comment]
Phase 1 will be completed by  https://github.com/chatwoot/chatwoot/issues/4990

**Comment by sojan-official** [comment]
There hasn't been much interest around providing this as a configuration for agents.  In most cases the business admin determines the limit and it is already available via capacity config. lets reopen if there in renewed interest.
