### ISSUE TITLE
feat: Assign conversation to the first responder when unassigned

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#2303]
### Conversations should be assigned to the responder

Show an alert to the agents in all conversations if those are not assigned to them and they are trying to reply to it. 

- [ ] When the user starts trying (clicks on the reply box) of a particular conversation which is not assigned to them, show a banner with a message "This conversation is not assigned to you, would you like to assign it to you? " -  "Assign to me"
- [ ] If "Assign to me" is clicked, Assign the conversation to the user.

**Todo:**

- [ ] Create a banner component, props: message, action (button title, onClick, href)
- [ ] Migrate existing banners to the banner component
- [ ] Implement the logic as mentioned above.

<img width="710" alt="Screenshot 2021-08-30 at 2 51 26 PM" src="https://user-images.githubusercontent.com/2246121/131317319-fcc4dc97-9554-4390-8df8-9b469042e038.png">
