### ISSUE TITLE
CSAT for every channel (backend)

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#2653]
Right now, CSAT surveys are supported only in the web-widget channel. To support CSAT surveys in all channels, we would start by sending a link once the conversation is resolved.

Once the conversation is resolved, the system should create a message with input_csat type. In each send_on_service listener, there should be an additional check to alter the content to send the link for the CSAT survey.

URL format: `<installation-url>/app/responses/<response-uuid>`

**Todo**:

- [x] #2671
- [ ] Update API to provide rating and response. Save the response in both the message object as well as the CSAT response object.
- [ ] Behaviour: 
   - [ ] Lock interaction based on the day: If the CSAT is a message sent more than 14 days before, then throw 404.
   - [ ] If already submitted, add an additional flag on the response to show that the message is submitted.

**Notes**

- Shouldn't work for twitter
