### ISSUE TITLE
Allow drag and drop for contact panel sections 

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#2794]
### Problem

The conversation has a sidebar that shows a list of sections related to the conversation lie contact details, assigned agent, etc. Currently, it is not possible to change the order of sections.

![drag-ndrop](https://user-images.githubusercontent.com/12408980/129560967-3a947f0e-86d3-48c1-8038-b98fb44a97fd.png)

### Solution

Add the ability to change the order of contact sections anywhere in the sidebar via drag and drop

### Todo

- [ ] Add [Vue.Draggable](https://github.com/SortableJS/Vue.Draggable) package
- [ ] Save the default order in the `ui_settings` attribute for a user.
- [ ] Use `draggable` component from **Vue.Draggable** library outside of sidemenu wrapper
- [ ] Save the order in `ui_settings` attribute if dragging is finished 

**Additional notes**

- Start only after completing the https://github.com/chatwoot/chatwoot/issues/2785
