### ISSUE TITLE
Channel icon is missing when the conversation is created

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#2815]
**Describe the bug**

<img width="393" alt="Screenshot 2021-08-14 at 2 29 15 PM" src="https://user-images.githubusercontent.com/2246121/129440823-38701adf-b0e6-4f4a-adac-0b7f3d440501.png">

When the conversation is created from Whatsapp/Twitter/Facebook, the icon indicating Whatsapp/Twitter/Facebook is missing until the page is reloaded.

**To Reproduce**

1. Send a message to a WhatsApp Channel
2. You would be able to see the conversation in the conversation list without the Whatsapp icon.

**Todos**

- [ ] The conversation should display the icon for Whatsapp on creation itself.
- [ ] Differentiate between Twitter DMs and Tweets.
- [ ] Verify icons for Twilio SMS / Whatsapp.
- [ ] Test the behaviour in all external channels.

**Comment by tejaswinichile** [comment]
@pranavrajs 
<img width="72" alt="twitter" src="https://user-images.githubusercontent.com/10827585/150135149-6da94bea-f41b-4558-9d69-f5999030cc32.png">

<img width="95" alt="whatsapp" src="https://user-images.githubusercontent.com/10827585/150135160-23d341bc-4983-47fa-a49e-5275693f840b.png">

I this has been fixed on production.
