### ISSUE TITLE
Add a toggle to disallow users to send messages after a conversation is resolved.

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#2827]
**Context:**

Right now, if the CSAT survey is enabled then we disallow the end-users to send a message when the conversation is resolved. This should be a configuration in the website channel settings.

**Todo:**

- [ ] Add a boolean variable, `allow_messages_after_resolved` to the inbox model. Set default value to true.
- [ ] Update the inbox APIs to include the boolean attribute.
- [ ] Change the widget implement to use `allow_messages_after_resolved` attribute instead of `csat_enabled` to show the new conversation button.

**Followup ticket:**

- [ ] How to handle resolution on external channels?
- [ ] Do we need to block the agent if the setting is enabled?
