### ISSUE TITLE
epic: End Conversation flow

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#2830]
**Context:** 
Right now, even if the user has got their solution, there is no way to close the conversation and move on. This has an impact on large organizations as they deal with a lot of requests and they would have to wait for the user to give a confirmation on their end to close the conversation.

**Things to do:**

- [x] https://github.com/chatwoot/chatwoot/issues/2827
- [x] https://github.com/chatwoot/chatwoot/issues/2828
- [ ] https://github.com/chatwoot/chatwoot/issues/2829

**Comment by brentco** [comment]
Would this also mean the user would see that a conversation gets closed from API? I believe this use case would be quite popular:

1. User opens the chat
2. Bot gives greeting
3. User goes through the bot's flow
4. On end states in the bot, the bot will need to close the conversation
5. User can no longer talk and on they get a button to start a new chat (or on next page refresh this is automatic)

The conversation closing right now is actually just setting the status to resolved via API, but right now that is not at all final.
Would this feature mean that conversations can be closed without the possibility to reopen them?

This is kind of a different approach to the "continuous conversation" type of chat Chatwoot offers now, and leans more towards a session based conversation lifetime. However, I think the latter is more suitable for automated flows.

**Comment by pranavrajs** [comment]
> Would this feature mean that conversations can be closed without the possibility to reopen them?

@brentco Yes, there will be a toggle that would help us achieve the same. https://github.com/chatwoot/chatwoot/issues/2827

"continuous conversation" will still be there. As per the feedback received, we figured that there is a need to have multiple threads of conversation with a customer. Having the same thread for different types of requests is often confusing.

**Comment by thepixelmonk** [comment]
how's this going?
