### ISSUE TITLE
feat: Ability to change notification sound

### ISSUE THREAD

**Issue by benphelps** [chatwoot/chatwoot#2983]
**Is your enhancement request related to a problem? Please describe.**
The default notification sound is very easy to miss.

**Describe the solution you'd like**
Have the option to choose between different sounds or upload your own custom sound.

**Describe alternatives you've considered**
Currently I replace the ding.mp3 manually myself with one from https://notificationsounds.com/

This is a collection of free to use Creative Commons licensed notification sounds, they would be easily included into the project without any licensing issues.

**Additional context**
Even the option between a few other choices would be fine, the current one is just too quiet and short.

**Comment by muhsin-k** [comment]
Chatwoot supports a audio  notifications in dashboard for new messages and conversations. But currently support only one sound.

### Problem

The current notification sound is short and easy to miss. 

### Solution

The user should have the option to choose between different sounds.

### Todos

- [ ] Find some sounds which are completely free to use
- [ ] Add  sound dropdown to choose near audio notification under profile settings
- [ ] Save the selected value in user `ui_settings` state
- [ ] Disable sound dropdown only audio notification is disabled

**Design**

<img width="481" alt="Screenshot 2021-09-11 at 5 01 16 PM" src="https://user-images.githubusercontent.com/12408980/133023012-08919ce5-1058-4d1b-84a2-99d7b2bae444.png">

### Followup investigation

- [ ]  Ability to upload custom sounds

**Comment by fdstevex** [comment]
This is a problem for us - agents are missing chat messages because they don't hear the little default click sound.

**Comment by calebjacobson** [comment]
our agents are also having the same problem. The default sound is too quiet, so they are missing many of the incoming messages and not responding as quickly as they should. Any ideas when alternate notifications/notification volume can be user specified?

**Comment by edryansaltat** [comment]
The agent-side audio notification sound doesn't seem to work for me. I've enabled it in the profile settings for 'All Conversations' but still won't work. This is a very crucial feature for me.

**Comment by GKG4** [comment]
Is it possible to add a custom sound like a ring or something, every time a new conversation is created and keeps ringing until click accepted or something?
This way, if the agent is not on his/her seat, can actually hear that sound and come back to reply.

**Comment by kubre** [comment]
Any updates over here?

**Comment by pranavrajs** [comment]
Closed via https://github.com/chatwoot/chatwoot/pull/6150
