### ISSUE TITLE
epic: Chatwoot Webhooks APIs

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3140]
The chatwoot webhooks API has been left out of some of the recent improvements and could do with refactoring. This epic covers the changes required. 

- [ ] feat: Support the full set of events: At the moment the webhooks only support a limited set of events like `conversation_status_changed` , `message_created` etc . ref: https://github.com/chatwoot/chatwoot/blob/develop/app/listeners/webhook_listener.rb
We want to support the other accounts events available here : https://github.com/chatwoot/chatwoot/blob/develop/lib/events/types.rb 
  - conversation: ( conversation created, assignee changed, team changed etc)  
  - CRM : (contact created, deleted, etc)
- [x] doc: Update documentation for usage / events  and payload format : https://github.com/chatwoot/docs/blob/main/docs/product/others/webhook-events.md
- [x] #4539
- [ ] chore: Validate agent bot events and ensure consistency. ( all newly added inbox scoped webhook events should be available for agent bots as well: conversation_created, team_changed, etc )
- [ ] chore: Validate API channels and ensure consistency. ( all newly added inbox scoped webhook events should be available for agent bots as well: conversation_created, team_changed, etc )
- [ ] chore: confirm webhook payloads contain the newer attributes like assignee_last_seen
- [ ] doc: Update product doc to list all the events available in webhooks : https://www.chatwoot.com/docs/product/features/webhooks 
- [ ] Include every type of message in the webhook callback.
- [x] Add an additional setting for webhook config to select the events the user want to subscribe to.

## Related Issues 

- [x] https://github.com/chatwoot/chatwoot/issues/3558
- [x] https://github.com/chatwoot/chatwoot/issues/3430
- [ ] https://github.com/chatwoot/chatwoot/issues/3238
- [x] https://github.com/chatwoot/chatwoot/issues/4267
- [x] https://github.com/chatwoot/chatwoot/issues/3536
- [x] https://github.com/chatwoot/chatwoot/issues/1645
- [ ] #4732

## References 

https://github.com/chatwoot/chatwoot/discussions/2905

**Comment by helpobras** [comment]
Sorry for the muted video. I do not speak English.
what happens is that when doing the manual assignment the action is not being sent to the webhook. when the conversation ends, the two actions are sent as shown in the video.
https://youtu.be/mI4UeNXzu0k

**Comment by sojan-official** [comment]
ref 
https://github.com/chatwoot/chatwoot/issues/3558
https://github.com/chatwoot/chatwoot/issues/3430
https://github.com/chatwoot/chatwoot/issues/3238

**Comment by franzvezuli** [comment]
Hello. Is it possible to `version` the webhook payloads that get sent? A top-level `version` would be good like
```
{
  "version": 1.0
}
```
```
{
  "version": 1.1
}
```

Or even better yet, if in the dashboard we can subscribe to a specific version of the webhook like so

![image](https://user-images.githubusercontent.com/4238855/159525714-6032fdc7-b1d7-4e1f-962a-b3f8359540f9.png)

I have noticed that multiple payloads are sent to my APIs during events -- and that the schema for those payloads vastly differs. I'm assuming these are older versions of webhook payloads vs new ones.

It would be great to get a more deterministic payload, and a schema that never changes (unless you opt in to a different version)

**Comment by sojan-official** [comment]
@franzvezuli  Thanks for the feedback, we will keep it in mind as we work over this epic.

**Comment by sojan-official** [comment]
Closing this since we don't track epics on github anymore, rather via individual issues.
