### ISSUE TITLE
feat: Automation rules

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#3195]
### Problem

There will be tons of repeatable tasks for any team that can be automated — like assigning a specific type of conversation to the right team or adding correct labels.

Ex: Suppose an agent receives a message from a premium customer in their chatwoot dashboard. Then, an agent can add the label "priority conversation" based on their plan and prioritize them. Now this flow is carried out manually. This kind of issue can solve by adding automation rules.

Automation can replace and automate existing processes that require manual effort. You can do many things with automation, including adding labels and assigning conversation to the best agent. So the team focuses on what they do best and spends more time on manual tasks.

Automation helps,

- The right team will always handle conversations and in the correct order.
- Increase teams' efficiency
- Preserve customers happiness
- Better workload management

### Solution

Automation rules consist of three parts, event, conditions, and actions. The list of defined actions will be performed sequentially when matching all the conditions after the specified event is triggered. As simple as "when, If this, then that." 

### Engineering Spec

**Back End**

**Data Model**

**Automation**

- automation_name → The name of the automation rule
- automation_description → Description about automation rule
- automation_trigger_count → Number of times automation executed
- automation_active → The automation is active or not
- automation_event ->  Events that qualify to start scanning for the automation conditions ex: Conversation is closed, Conversation is opened, Label is added, Label is removed, Assignee changes to, etc.
- automation_conditions -> Filters for any conditions that a conversation or contact must meet for the actions to apply.
- autmation_actions → Actions specify the actions that will result when the rule is processed successfully (when all filter conditions are met). All the actions will execute sequentially once the rule condition is met (at Atleast minimum, one action is required) ex: Send Message (Option to send a message), Update custom fields, Assign conversation, etc

**Front End**

- Create a new page called "Automations" under the settings page
- Show a button at the top of the page called "Add automation."
- On clicking the "Add automation" button, show a modal. Add the ability to create new automation using automation_name, automation_description, automation_event, automation_conditions and autmation_actions
- Supports pagination and filter
- Add the ability to clone/edit/delete automation from the table

### Todo

- CRUD APIs for automation (Account level)
- Create a new route Automations under the settings page
- Add the option to create a new automation rule
- Add the option to clone/edit/delete automation rule
- List automation rules in a table
- Background job for executing the automation

### Success metrics

- Automation rules help your team's workflows for optimum efficiency and ensure your customers get the best experience possible.
- Automations rules save time in the long run.
- Every customer should get the best answer as fast as possible.

### Questions

- Is the automation rule works in all inboxes?
- Priority of rules 

### Frontend

- [x] #3575
- [x] #3576

**Comment by tejaswinichile** [comment]
Params structure we are getting at backend [API]

```ruby
{
  automation_name: "Some Name"
  automation_description: "Some Description"
  automation_event: "Conversation Created"{dropdown}
  automation_conditions [
    {
      select attribute: COUNTRY/MESSAGE_CONTENT/BROWSER_LANGUAGE
      select operator: IS/IS NOT/EQUALS TO/NOT EQUAL TO/CONTAINS/ DOES NOT CONTAINS'
      select value: Myanmar
    }
  ]
  automation_actions: [
    Send Message: { Message: value },
    Add Lable: [ priority_customer ],
    Assign best agents: [ Mutiselct of agents ]
    Update Custom Attributes: [
      attribute_key: attribute_value
    ]
    Pin the conversation: /* future scope */
  ]
}
```
Example 1: 

```ruby
{
  automation_name: "Paid Plan: Conversation Automation"
  automation_description: "Silver Paid Plan, Customer Conversation Automation"
  automation_event: "Conversation Created" {dropdown}
  automation_conditions: [
    {
      automation_conditions_attribute: plan /* Custome Attribute */
      automation_conditions_operator: EQUALS TO
      automation_conditions_value: Silver
    },
    {
      automation_conditions_attribute: Country /* Custome Attribute */
      automation_conditions_operator: EQUALS TO
      automation_conditions_value: USA
    }
  ]
  automation_actions: [
    Send Message: 
      { 
        Message: 'Welcome to the chatwoot platform.' 
      },
    Add Lable: [ priority_customer ],
    Assign Best Agents: [ 1,2,3,4 ] /*  Dropdown Agent Names */
    Update Additional Attributes: [
      intiated_at: Time.now
    ]
  ]
}
```


Meta Data for attributes and conditions

***********************************************************************
conditions we are supporting

```js
attribute    table_name 

plan:        contact_custome_attribute
country:     contact
date_range:  conversation created

```
***********************************************************************
actions we are supporting

```js
1. send_message
2. send_email, 
3. add_label, 
4. add_best_agents, 
5. update_additional_attribute
6. assign_best_agents
7. send_survey
```

***********************************************************************
automation_event  we are supporting
```js
1. Conversation Created: 
   [send_message, send_email, add_label, add_best_agents, update_additional_attributes]

2. Conversation Closed: 
   [send_message, send_email, add_label, update_additional_attributes]

2. Conversation Resolved: 
   [send_message, send_email, add_label, update_additional_attributes, send_survey]

3. Assigned: 
   [send_message, send_email, add_label, update_additional_attributes]

4. Label Added
   [send_message, send_email, update_additional_attributes]
```

**Comment by tejaswinichile** [comment]
Params structure we are getting at backend [API]

```ruby
{
  automation_name: "Some Name"
  automation_description: "Some Description"
  automation_event: "Conversation Created"{dropdown}
  automation_conditions [
    {
      select attribute: COUNTRY/MESSAGE_CONTENT/BROWSER_LANGUAGE
      select operator: IS/IS NOT/EQUALS TO/NOT EQUAL TO/CONTAINS/ DOES NOT CONTAINS'
      select value: Myanmar
    }
  ]
  automation_actions: [
    Send Message: { Message: value },
    Add Lable: [ priority_customer ],
    Assign best agents: [ Mutiselct of agents ]
    Update Custom Attributes: [
      attribute_key: attribute_value
    ]
    Pin the conversation: /* future scope */
  ]
}
```
Example 1: 

```ruby
{
  automation_name: "Paid Plan: Conversation Automation"
  automation_description: "Silver Paid Plan, Customer Conversation Automation"
  automation_event: "Conversation Created" {dropdown}
  automation_conditions: [
    {
      automation_conditions_attribute: plan /* Custome Attribute */
      automation_conditions_operator: EQUALS TO
      automation_conditions_value: Silver
    },
    {
      automation_conditions_attribute: Country /* Custome Attribute */
      automation_conditions_operator: EQUALS TO
      automation_conditions_value: USA
    }
  ]
  automation_actions: [
    Send Message: 
      { 
        Message: 'Welcome to the chatwoot platform.' 
      },
    Add Lable: [ priority_customer ],
    Assign Best Agents: [ 1,2,3,4 ] /*  Dropdown Agent Names */
    Update Additional Attributes: [
      intiated_at: Time.now
    ]
  ]
}
```


Meta Data for attributes and conditions

***********************************************************************
conditions we are supporting

```js
attribute    table_name 

plan:        contact_custome_attribute
country:     contact
date_range:  conversation created

```
***********************************************************************
actions we are supporting

```js
1. send_message
2. send_email, 
3. add_label, 
4. add_best_agents, 
5. update_additional_attribute
6. assign_best_agents
7. send_survey
```

***********************************************************************
automation_event  we are supporting
```js
1. Conversation Created: 
   [send_message, send_email, add_label, add_best_agents, update_additional_attributes]

2. Conversation Closed: 
   [send_message, send_email, add_label, update_additional_attributes]

2. Conversation Resolved: 
   [send_message, send_email, add_label, update_additional_attributes, send_survey]

3. Assigned: 
   [send_message, send_email, add_label, update_additional_attributes]

4. Label Added
   [send_message, send_email, update_additional_attributes]
```

**Comment by muhsin-k** [comment]
## Supported automation condition attributes

#### Standard Attributes

- Status - Open / Resolved / Pending / Snoozed / All
- Assignee - Person or None
- Contact - Contact or None
- Message (Support regex)
- Inbox
- Team
- ID 
- Label or Labels

### Additional Attributes

- Browser
- City
- Country_code
- referer

### Contact fields

### Standard fields

- email
- name
- phone_number
- last_activity_at
- identifier

#### Additional Attributes
- city
- country_code

---
## Supported operators

- Equal to 
- Not Equal 
- Is present
- Is not present
- Contains
- Does not contain
- Greater than (number, date)

**Comment by muhsin-k** [comment]
Automation events  we are supporting,
```js
1. Conversation Created
2. Conversation Resolved
3. Assigned
4. Label Added
5. Label Removed
6. Conversation Snoozed
7. Conversation Auto Resolved
8. Conversation Muted
9. Team Assigned
10. New message created (Incoming/Outbound)

```

***********************************************************************
Automation conditions  we are supporting,


```js
1. Select inbox (Option to select all or some inboxes)
2. Status - Open / Resolved / Pending / Snoozed / All
3. Contact - Contact or None
4. Team
4. Label or Labels
3. Message (Support regex)
3. Assignee - Person or None
2. Custom attributes (Contact or Conversation)
3. Additional attributes (Browser, City, Country_code, referer)
4. Contact fields (email, name, phone_number, last_activity_at, identifier)
```

***********************************************************************

***********************************************************************
Automation actions  we are supporting,


```js
1. Send Message
2. Send Email
3. Resolve Conversation
4. Add Label
5. Update custom/additional attributes
6. Remove label
7. Snooze Conversation
8. Assign to agent
8. Assign to team
9. Send Transcript
10. Add support for sending webhook event 
```

***********************************************************************

**Comment by voko3456** [comment]
@muhsin-k @aswindevps @pranavrajs @tejaswinichile can you add automation action to send interactive session message so customer can replay by clicking the button and save his replay on custom attributes so we can implement local chat bot example :
![whatsapp_illu_main_header_interactive_buttons_](https://user-images.githubusercontent.com/20530550/138146898-ebe16dd3-6e95-4bb8-a51f-4fd0bb574ae0.png)

![Screenshot_20211020-210436_Instagram](https://user-images.githubusercontent.com/20530550/138147246-41f3b34f-adff-4355-b37b-1d53b1fdeab5.jpg)

**Comment by voko3456** [comment]
> ## Automation events
> ```js
> 1. Conversation Created
> 2. Conversation Resolved
> 3. Assigned
> 4. Label Added
> 5. Label Removed
> 6. Conversation Snoozed
> 7. Conversation Auto Resolved
> 8. Conversation Muted
> 9. Team Assigned
> 10. New message created (Incoming/Outgoing)
> ```

@muhsin-k 
Please Add events 
11-custom attributes updated
12-time since last message

**Comment by tejaswinichile** [comment]
@voko3456 It's pretty early to quote if we can fulfill your requirement mentioned here https://github.com/chatwoot/chatwoot/issues/3195#issuecomment-947911895 in the next release, but we can have an initial message to send to the customer,
  
1. if suppose the customer message contains a question related to food then we can send the related message as a reply. 

After that how would we save the customer response, will take some time to decide. 

But thanks for the requirement we would like to have that in our support system we would track that requirement in the different ticket.

**Comment by tejaswinichile** [comment]
- [ ] Endpoint to receive conversation automation rules and save the automation actions: https://github.com/chatwoot/chatwoot/issues/3341
- [ ] Perform automation actions based on rules ttps://github.com/chatwoot/chatwoot/issues/3342

**Comment by tejaswinichile** [comment]
@sojan-official 
Since we are handling dynamic event action trigger based on conditions, we need to have a publish-subscribe pattern to handle such implementation. Where subscribers will continuously listen to the event is being called and we will publish the event only when the condition matches. https://ably.com/topic/pub-sub I am thinking to add a gem for Automation Rules event handling. 

We can do it without gem too but it will just fatten the models.  
There are gems that can handle publish and subscribe patterns in rails. 

Here are some examples:
1. https://github.com/krisleech/wisper
2. https://github.com/kevinrutherford/event_bus
3. https://github.com/stevo/pubsub_on_rails

Please let me know if you think otherwise.

cc @pranavrajs @muhsin-k

**Comment by sojan-official** [comment]
@tejaswinichile  Sounds like a good direction. we already have pubsub mechanism in chatwoot using the wisper gem. 
https://github.com/chatwoot/chatwoot/blob/a34bb565af4604767c870e8ede72674f82d0de81/Gemfile#L75

We can refactor and enhance the current list of events to support all the required event types. 
https://github.com/chatwoot/chatwoot/blob/a34bb565af4604767c870e8ede72674f82d0de81/lib/events/types.rb#L3

We can also add an automation listener which will react to these events based on the account configuration
https://github.com/chatwoot/chatwoot/blob/0c9b682329489c4a1a2fe5258db98b68153470f6/app/listeners/campaign_listener.rb#L2

**Comment by tejaswinichile** [comment]
@sojan-official Okay then I will use the same gem. Thanks :)

**Comment by muhsin-k** [comment]
**Front End**
- [ ] feat: Automations route
- [ ] feat: Add the ability to create a new automation rule
- [ ] feat: Automations table
- [ ] feat: Add the ability to edit/delete/clone automation rules

**Comment by tejaswinichile** [comment]
@muhsin-k
Just to confirm 
`Automation conditions` will be applied to the conversation record which is mentioned in `automation_event`, correct?
Like if we have automation_event on conversation created and conditions browser language `en`  so this condition will be applied on the record that was created in a recent event, right?

**Comment by tejaswinichile** [comment]
@sojan-official @muhsin-k 
MVP for automation rule: 

**Event: Message Created**

Supported Condition: 
1. Filter on message type [Incoming and outgoing] 
2. FIlter on substring e.g message contains words related to price assign it to the finance support team.
Supported Actions: 
1. Assign a team
2. Send an email to the team


**Event: Conversation Created**

Supported Condition: 
1. Filter on conversation status [equal_to/not_equal_to]
2. browser_name
3. country_name
4. referer link

Supported Actions: 
1. Assign a team
2. Send an email to the team
3. Assign an agent

**Event: Conversation Updated**

Supported Condition: 
1. Filter on conversation status [equal_to/not_equal_to]
2. browser_name
3. Assignee_id 
4. team_id 
5. country name
6. referer link
Supported Actions: 
1. Assign a team
2. Send an email to the team
3. Assign an agent

**Comment by tejaswinichile** [comment]
One update:

```rb
automation_actions: [
    Send Message: { Message: value },
    Add Label: [ priority_customer ],
    Assign best agents: [ Mutiselct of agents ]
    Update Custom Attributes: [
      attribute_key: attribute_value
    ]
    Pin the conversation: /* future scope */
  ]
```

Would look like this:
```rb
automation_actions: [
    { 
        action_name: send_message,
        action_params: 'Welcome aboard!' 
    },
    { 
        action_name: add_label,
        action_params: [priority_customer, finance_query] 
    },
    { 
        action_name: assign_agents,
        action_params:  [1,2,3,4] 
    },
    update_custom_attributes: [
      { attribute_key_1: attribute_value_1 },
      { attribute_key_2: attribute_value_2 }
    ]
  ]
```
@muhsin-k Please take note of this change.

**Comment by voko3456** [comment]
> One update:
> 
> ```ruby
> automation_actions: [
>     Send Message: { Message: value },
>     Add Label: [ priority_customer ],
>     Assign best agents: [ Mutiselct of agents ]
>     Update Custom Attributes: [
>       attribute_key: attribute_value
>     ]
>     Pin the conversation: /* future scope */
>   ]
> ```
> 
> Would look like this:
> 
> ```ruby
> automation_actions: [
>     { 
>         action_name: send_message,
>         action_params: 'Welcome aboard!' 
>     },
>     { 
>         action_name: add_label,
>         action_params: [priority_customer, finance_query] 
>     },
>     { 
>         action_name: assign_agents,
>         action_params:  [1,2,3,4] 
>     },
>     update_custom_attributes: [
>       { attribute_key_1: attribute_value_1 },
>       { attribute_key_2: attribute_value_2 }
>     ]
>   ]
> ```
> 
> @muhsin-k Please take note of this change.

@tejaswinichile @muhsin-k please don't forget to add the most important action is to send webhook when custom attributes updated or label added

**Comment by tejaswinichile** [comment]
**Notes:** 
Assign Teams: We assign only one team, so team dropdown would have a single selection.

Assign Best Agent: We assign only one agent, so the agent's dropdown would have a single selection.

Send email to the team: The team should be part of the account. This will require 2 params, one for team ids and the other for the email content.

**Comment by sojan-official** [comment]
@tejaswinichile  @muhsin-k potential use case 

When phone number attribute of a contact gets updated 'Create conversation in an external Inbox with a specific message' 

- Trigger a WhatsApp conversation with a user through API
- Switch the communication to SMS channel from live chat


ref:  https://discord.com/channels/647412545203994635/719548534302441565/920414786691432548
