### ISSUE TITLE
feat: Support location messages in chatwoot

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3398]
Various channels like Facebook messenger, WhatsApp, etc support location messages. The ability for chatwoot to render these messages properly

## Tasks 
- [x] Build a location message component for the Chatwoot dashboard 
- [ ] Audit the channels that support location messages
- [ ] Make code changes and ensure those messages are rendered in chatwoot correctly

**Comment by sanjayws** [comment]
hi @sojan-official can you please assist where would i start if i wanted to build a quick hack for this? Would you be kind enough to point out the file(s) that i need to look at?

Thanks

**Comment by sojan-official** [comment]
@sanjayws  Chatwoot during its inception had support for location messages from Facebook. So we have some leftover code that you could leverage. 

message objects in chatwoot can have attachments. you can use attachment objects to store your location coordinates 
ref: https://github.com/chatwoot/chatwoot/blob/1c99294c8c52f3780ff73c7a6ffa892d2ce2b4a7/app/models/attachment.rb#L69

The easiest approach to getting started with this would be to pick up a specific channel with location messages support.  
ie - > facebook, WhatsApp etc. 

> LiveChat would require us to build an interface for both the contacts and visitors to pick a location.

-----

So for the start lets scope it down to  
- Incoming location data gets parsed and stored in message attachments in a specific channel
- render the location message attachments in the agent dashboard 

ref: https://github.com/chatwoot/chatwoot/blob/1c99294c8c52f3780ff73c7a6ffa892d2ce2b4a7/app/javascript/dashboard/components/widgets/conversation/Message.vue#L26


will be happy to collaborate over a PR.

**Comment by sanjayws** [comment]
Mr Sojan, i am not a Ruby dev, but i will try to look into this based on your guidance here. As i've said earlier, i will elated to work with the CW team by means of supporting the prioritisation of this and we can discuss this more.

Happy New Year and stay safe.

**Comment by sanjayws** [comment]
Hello. Happy new year. Anyway we can up priority this? 

Appreciate all your work.

**Comment by loama** [comment]
Hi, I got a workaround to this, I am using twilio for whatsapp so I created a function to process the location messages received and send them as text to chatwoot.

Based on this guide: https://www.twilio.com/blog/glorious-food#:~:text=Getting%20Location%20Data%20from%20WhatsApp,and%20an%20address%20if%20available.

Here is my code for the twilio function:

```
const axios = require('axios')

exports.handler = async function handler(context, event, callback) {
  let twiml = new Twilio.twiml.MessagingResponse();
  
  let newEvent = JSON.parse(JSON.stringify(event));
  
  if (!event.Latitude || !event.Longitude) {
    // do nothing, handle it normally
  } else {
    const location = {
      lat: event.Latitude,
      lon: event.Longitude
    };

    newEvent.Body = `Mensaje de ubicación: https://www.google.com/maps?q=${location.lat},${location.lon}`;
  }
  
  axios
      .post('https://amiloz-chatwoot-custom.herokuapp.com//twilio/callback',
        newEvent
      )
      .then(() => {
          callback(null, twiml);
      })
      .catch(error => {
        callback(error);
      })
}
```

It sends the location as a text message with a link to google maps.
It isn't perfect, I would have prefered to load gmaps directly into the chat, but this was only a few hours of work and didn't require me to get into chatwoot code.

Hope this helps someone.
@sanjayws @sojan-official

**Comment by sanjayws** [comment]
Thank you. Still hopeful it will be made a hotfix or release. It is an important function. 

Now I need to figure it out with 360Dialog 

Thanks again. 🙏🏾

**Comment by sojan-official** [comment]
@sanjayws Whatsapp location messages are now supported in Chatwoot Cloud for both 360 Dialogue & Whatsapp Cloud. 
It will be available in the upcoming Chatwoot release for self-hosted instances. 

<img width="611" alt="Screenshot 2022-11-08 at 3 32 01 PM" src="https://user-images.githubusercontent.com/73185/200698390-7db028e0-5a73-40c6-8e3b-55199a56d1eb.png">

**Comment by sanjayws** [comment]
Thanks @sojan-official appreciate your effort and thanks for updating here too.

**Comment by sojan-official** [comment]
@Kr00t only incoming location messages are supported at the moment.

**Comment by dantevls** [comment]
> @sanjayws Whatsapp location messages are now supported in Chatwoot Cloud for both 360 Dialog & Whatsapp Cloud. It will be available in the upcoming Chatwoot release for self-hosted instances.
> 
> <img alt="Screenshot 2022-11-08 at 3 32 01 PM" width="611" src="https://user-images.githubusercontent.com/73185/200698390-7db028e0-5a73-40c6-8e3b-55199a56d1eb.png">

Could you send a example request in postman ?

**Comment by jmelati** [comment]
> @sanjayws Whatsapp location messages are now supported in Chatwoot Cloud for both 360 Dialog & Whatsapp Cloud. It will be available in the upcoming Chatwoot release for self-hosted instances.
> 
> <img alt="Screenshot 2022-11-08 at 3 32 01 PM" width="611" src="https://user-images.githubusercontent.com/73185/200698390-7db028e0-5a73-40c6-8e3b-55199a56d1eb.png">

Do you have an example in curl?

**Comment by sojan-official** [comment]
@jmelati @dantevls please refer : https://github.com/chatwoot/chatwoot/pull/5742

**Comment by BossBuusMuus** [comment]
It's not clear what the request body is supposed to like. Can someone just share it.

**Comment by Hsilamot** [comment]
I have to comment this, i have self-hosted 3.5.2 and locations are still empty messages, alongside reactions and other stuff.

THe Twilio workaround of @loama worked perfectly fine, if anyone is looking for it, the workaround is quite simple, you create a function in Twilio functions which gives you an endpoint, to where you point your Twilio's Messaging Service messages towards, and from that code it sends the message to your chatwoot's endpoint.

it's somewhat sad how poor the support is for the self-hosted solutions, feature-wise, we used the Cloud based solution and it is way more complete and feature rich than the "leftovers" of the self-hosted option.

Thanks again for the workaround.

**Comment by sojan-official** [comment]
@Hsilamot, The feature set on the self-hosted solution and the cloud is the same.  The cloud solution is yet another hosted version of this repo managed by the chatwoot team.  We don't have a separate code base for the cloud.

**Comment by Hsilamot** [comment]
> @Hsilamot, The feature set on the self-hosted solution and the cloud is the same. The cloud solution is yet another hosted version of this repo managed by the chatwoot team. We don't have a separate code base for the cloud.

i thank you for your reply, the perception is mainly focused on the fact that the self hosted solution appears to have some functionality disabled, but your reply has made me think that we are doing something wrong, we are going to try to use docker or other way to deploy to see if our deployments have been done wrong.

**Comment by pranavrajs** [comment]
Closing this via https://github.com/chatwoot/chatwoot/pull/11830
