### ISSUE TITLE
feat: Consider business hours while generating the reports

### ISSUE THREAD

**Issue by tejaswinichile** [chatwoot/chatwoot#3446]
**Is your enhancement request related to a problem? Please describe.**
We are not considering the week's off days now while generating the report which affects the average resolution time.

**Describe the solution you'd like**
We should consider the week's off days that we mention in the settings while generating the report.

**Describe alternatives you've considered**
While generating the report deduct the number of off days.

**Additional context**
Refer: https://app.chatwoot.com/app/accounts/1/conversations/11059

### Todo:
- [x] #4057
- [ ] Add a value_in_business_hours, event_start_time, event_end_time. In the migration, use nil as existing value.
- [ ] Compute value_in_business_hours while creating the event. If all_day, then value = value_in_business_hours. If not all_day, compute the difference in hours
- [ ] Add toggle near the graph to see values_in_business_hours.

**Comment by tejaswinichile** [comment]
<img width="400" alt="report_fix" src="https://user-images.githubusercontent.com/10827585/142990603-1d680579-6517-478e-924a-fc69ed6c82a8.png">

**Comment by aswindevps** [comment]
@pranavrajs Need more investigation. Hence adding back to Icebox.

**Comment by sojan-official** [comment]
@pranavrajs Since this would change the behaviour of calculations of the metrics, Should we enable it based on a setting ?

- probably a checkbox near the business hours configuration / or in reports  ( Calculate reports based on business hours? )

**Comment by pranavrajs** [comment]
- [ ] Add a value_in_business_hours, event_start_time, event_end_time. In the migration, use nil as existing value.
- [ ] Compute value_in_business_hours while creating the event. If all_day, then value = value_in_business_hours. If not all_day, compute the difference in hours
- [ ] Rename events to reporting_events
- [ ] Add toggle near the graph to see values_in_business_hours.
