### ISSUE TITLE
Bug: Problem importing contacts info

### ISSUE THREAD

**Issue by JosueRTV** [chatwoot/chatwoot#3462]
**Describe the bug**
Problem importing contacts info

When importing the csv file with id, name, identifier, email, and phone_number the phone_number and id are saved as custom_attribute

**To Reproduce**

Steps to reproduce the behavior

1. Generate CSV file with id, name, identifier, email, phone_number
2. In contacts select import > Browser > select file > import
3. Find the created contact (s) and note id and phone_number in custom_attributes

**Expected behavior**

phone number correctly saved in the corresponding column 

**Screenshots**
![image](https://user-images.githubusercontent.com/38108980/143302202-303ed276-128a-444c-98bc-cb4bcac2a226.png)

![image](https://user-images.githubusercontent.com/38108980/143303745-87c1de93-12b0-4ddc-aba6-4b04fb77536a.png)

**Environment**

Self hosted installation Docker/Linux in EKS, using Nginx as reverse proxy.
using chatwoot version: v1.21.1

**Desktop:**
 - OS X, linux 
 - Browser: chrome, firefox

**Additional context**

nginx config:

    upstream chatwoot {
      server chatwoot:3000;
    }
    upstream letsencrypt-chatwoot {
      server letsencrypt-chatwoot:80;
    }
    server {
      listen 80;
      listen [::]:80;
      server_name  chatwoot.my-cool-dns.com;
      location ^~ /.well-known/acme-challenge/ {
        proxy_pass http://letsencrypt-chatwoot;
      }
      location / {
        return 301 https://chatwoot$request_uri;
      }
    }
    server {
      listen 443 ssl;
      listen [::]:443 ssl;
      server_name  chatwoot.my-cool-dns.com;
      underscores_in_headers on;
      ssl_certificate     /etc/nginx/ssl/chatwoot/tls.crt;
      ssl_certificate_key /etc/nginx/ssl/chatwoot/tls.key;
      location / {
        proxy_pass http://chatwoot;
        proxy_pass_header Authorization;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
      }
    }

**Comment by sojan-official** [comment]
Was able to replicate this on my end. We will take it up for the upcoming release. 

## TODO

- [ ] Phone number doesn't get updated currently to contact attribute, instead of to a custom attribute
- [ ] Confer with contact merge logic when a duplicate phone number exists 
- [ ] Should support company attribute

### Changes required

#### Backend
https://github.com/chatwoot/chatwoot/blob/c2519ea1eabfb34f02c8df23740f1dbd423c6d52/app/jobs/data_import_job.rb#L30 
- [ ] include identification by phone number
- [ ] Discard phone number if duplicate contact found with different email or perform the merge

https://github.com/chatwoot/chatwoot/blob/c2519ea1eabfb34f02c8df23740f1dbd423c6d52/app/jobs/data_import_job.rb#L22
- [ ] Ensure additional attributes like the company are assigned

#### Frontend
- [ ] Update sample csv with company field

**Comment by Abhay907** [comment]
> get_identified_contacts
i am unable to find import/bulk import contacts logic. Please help me out

**Comment by sojan-official** [comment]
> > get_identified_contacts
> > @sojan-official
> 
> i am unable to find import/bulk import contacts logic. ? **And** how to use/do import/bulk import contacts using API? unable to find API reference


ref: https://www.postman.com/chatwoot/workspace/chatwoot-apis/request/162770-4290c9b1-dd56-45a3-b25e-cc5ce3a65298  ( this is the API end point )

**Comment by mattiamarras** [comment]
Sorry, I have not understand which workaround should I use to import the contact, I am trying to import my customer list (6.000 rows) but without success. The software respond "Contacts saved successfully" but is not true. I am using the v2.4.0.

**Comment by sojan-official** [comment]
@mattiamarras  you could write a script that will iterate over the contact lists and create contacts using the contact create API.  Meanwhile, we are looking into the bugs in import contacts.

**Comment by mattiamarras** [comment]
@sojan-official i made a script with php in order to import 6.000 contacts through API but often i obtain this error.
How can I solve this issue? It happens also if I limit to one request per second.

Retry later
Retry later
Retry later
Retry later
Retry later
Retry later
Retry later
Retry later
Retry later
Retry later
Retry later
Retry later
Retry later

**Comment by sojan-official** [comment]
@mattiamarras  are you working on a self-hosted instance? If so set the environment variable `ENABLE_RACK_ATTACK=false`

**Comment by mattiamarras** [comment]
@sojan-official self-hosted, i add the varible to the env file and then restart the service or the machine?
thank you

**Comment by sojan-official** [comment]
@mattiamarras  that is correct.

**Comment by mattiamarras** [comment]
Ok, problem solved.

**Comment by MaoBueno** [comment]
Hello @sojan-official 
Is there any update about this contact import issue?

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/product/issues/593

**Comment by KarzounApps** [comment]
> ref: https://github.com/chatwoot/product/issues/593

Hi there, link doesn't open, I think issue still persist

**Comment by weslanra** [comment]
This task has been open since 2021, do you have a correction forecast?
