### ISSUE TITLE
[CW-35] epic: Reporting improvements

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3570]
Collection of tech debts and Chores associated with reporting in chatwoot

* [ ] [https://github.com/chatwoot/chatwoot/issues/3242](https://github.com/chatwoot/chatwoot/issues/3242) ( possible issue with timezones, filters sending local time while the events stored in the backend are in UTC )
* [ ] **Clean up the tech debt associated with reporting v1**
  * [X] Rename events table to reporting_events or something more unique ( potential confusion when we add CRM events ) ( ref: [https://github.com/chatwoot/chatwoot/blob/develop/app/models/event.rb](https://github.com/chatwoot/chatwoot/blob/develop/app/models/event.rb) )
  * [ ] Clean up the leftover code from reporting v1
    1. [https://github.com/chatwoot/chatwoot/blob/develop/app/listeners/reporting_listener.rb](https://github.com/chatwoot/chatwoot/blob/develop/app/listeners/reporting_listener.rb)
    2. [https://github.com/chatwoot/chatwoot/tree/develop/lib/reports](https://github.com/chatwoot/chatwoot/tree/develop/lib/reports)
    3. [https://github.com/chatwoot/chatwoot/blob/develop/app/helpers/api/v1/reports_helper.rb](https://github.com/chatwoot/chatwoot/blob/develop/app/helpers/api/v1/reports_helper.rb)
    4. Any leftover code not associated with reports
* [ ] **Inconsistencies in resolutions time**: if a conversation gets reopened again after the initial resolution and then it gets resolved a second time, The second resolution event takes into account the entire time right from the start.
  This could impact greatly if a really old conversation was reopened by the contact again and the agent has to resolve it.
* [X] [https://github.com/chatwoot/chatwoot/issues/3446](https://github.com/chatwoot/chatwoot/issues/3446)
* [X] \#4028

---

* [X] \#4039
* [X] \#4040
* [X] \#4042
* [X] \#4041
* [X] Show the number of conversations in each group in the avg computation
* [ ] Deeper analysis of conversations
* [X] \#4043
* [X] [https://github.com/chatwoot/product/issues/377](https://github.com/chatwoot/product/issues/377)
* [X] [https://github.com/chatwoot/product/issues/364](https://github.com/chatwoot/product/issues/364)
* [X] [https://github.com/chatwoot/product/issues/418](https://github.com/chatwoot/product/issues/418)
* [X] [https://github.com/chatwoot/chatwoot/issues/4744](https://github.com/chatwoot/chatwoot/issues/4744)

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-35](https://linear.app/chatwoot/issue/CW-35/epic-reporting-improvements)</sub>

**Comment by pranavrajs** [comment]
@sojan-official Added timezone option in reports.

**Comment by rahulmr** [comment]
@sojan-official Do we have download CSAT Report option available? If not is it possible to implement such a button at the top corner? I tried to add such button at my end but the data is not coming properly.   
 I want to download 2 types of data -   

1.  After applying date and agent filter it should download all pages. 
2. It should download only current page.

**Comment by sojan-official** [comment]
@rahulmr  At the moment we don't have a download option for CSAT reports.

**Comment by rahulmr** [comment]
@sojan-official No issues, I was able to implement the same and it is working great.

Sorry no PR to submit but here is the code. You can refactor and add it in a better way.

```
<template>
  <div class="csat--table-container">
    <woot-button
      color-scheme="success"
      class-names="button--fixed-right-top"
      icon="arrow-download"
      @click="downloadCSATReports"
    >
      Download CSAT Reports
    </woot-button>
    <ve-table
      max-height="calc(100vh - 35rem)"
      :fixed-header="true"
      :columns="columns"
      :table-data="tableData"
    />
    <div v-show="!tableData.length" class="csat--empty-records">
      {{ $t('CSAT_REPORTS.NO_RECORDS') }}
    </div>
    <div v-if="metrics.totalResponseCount" class="table-pagination">
      <ve-pagination
        :total="metrics.totalResponseCount"
        :page-index="pageIndex"
        :page-size="25"
        :page-size-option="[25]"
        @on-page-number-change="onPageNumberChange"
      />
    </div>
  </div>
</template>
<script>
import { VeTable, VePagination } from 'vue-easytable';
import UserAvatarWithName from 'dashboard/components/widgets/UserAvatarWithName';
import { CSAT_RATINGS } from 'shared/constants/messages';
import { mapGetters } from 'vuex';
import timeMixin from 'dashboard/mixins/time';
import fromUnixTime from 'date-fns/fromUnixTime';
import format from 'date-fns/format';
import { downloadCsvFile } from '../../../../../helper/downloadCsvFile';

export default {
  components: {
    VeTable,
    VePagination,
  },
  mixins: [timeMixin],
  props: {
    pageIndex: {
      type: Number,
      default: 1,
    },
  },
  computed: {
    ...mapGetters({
      uiFlags: 'csat/getUIFlags',
      csatResponses: 'csat/getCSATResponses',
      metrics: 'csat/getMetrics',
    }),
    columns() {
      return [
        {
          field: 'contact',
          key: 'contact',
          title: this.$t('CSAT_REPORTS.TABLE.HEADER.CONTACT_NAME'),
          align: 'left',
          width: 200,
          renderBodyCell: ({ row }) => {
            if (row.contact) {
              return <UserAvatarWithName size="24px" user={row.contact} />;
            }
            return '---';
          },
        },
        {
          field: 'assignedAgent',
          key: 'assignedAgent',
          title: this.$t('CSAT_REPORTS.TABLE.HEADER.AGENT_NAME'),
          align: 'left',
          width: 200,
          renderBodyCell: ({ row }) => {
            if (row.assignedAgent) {
              return (
                <UserAvatarWithName size="24px" user={row.assignedAgent} />
              );
            }
            return '---';
          },
        },
        {
          field: 'rating',
          key: 'rating',
          title: this.$t('CSAT_REPORTS.TABLE.HEADER.RATING'),
          align: 'center',
          width: 80,
          renderBodyCell: ({ row }) => {
            const [ratingObject = {}] = CSAT_RATINGS.filter(
              rating => rating.value === row.rating
            );
            return (
              <span class="emoji-response">{ratingObject.emoji || '---'}</span>
            );
          },
        },
        {
          field: 'feedbackText',
          key: 'feedbackText',
          title: this.$t('CSAT_REPORTS.TABLE.HEADER.FEEDBACK_TEXT'),
          align: 'left',
          width: 220,
        },
        {
          field: 'converstionId',
          key: 'converstionId',
          title: 'details',
          align: 'right',
          width: 120,
          renderBodyCell: ({ row }) => {
            const routerParams = {
              name: 'inbox_conversation',
              params: { conversation_id: row.conversationId },
            };
            return (
              <div class="text-right">
                <router-link to={routerParams}>
                  {`#${row.conversationId}`}
                </router-link>
                <div class="csat--timestamp" v-tooltip={row.createdAt}>
                  {row.createdAgo}
                </div>
              </div>
            );
          },
        },
      ];
    },
    tableData() {
      return this.csatResponses.map(response => ({
        contact: response.contact,
        assignedAgent: response.assigned_agent,
        rating: response.rating,
        feedbackText: response.feedback_message || '---',
        conversationId: response.conversation_id,
        createdAgo: this.dynamicTime(response.created_at),
        createdAt: this.messageStamp(response.created_at, 'LLL d yyyy, h:mm a'),
      }));
    },
  },
  methods: {
    onPageNumberChange(pageIndex) {
      this.$emit('page-change', pageIndex);
    },
    JSONToCSVConvertor(JSONData, ShowLabel) {
      //If JSONData is not an object then JSON.parse will parse the JSON string in an Object
      var arrData = typeof JSONData != 'object' ? JSON.parse(JSONData) : JSONData;
      var CSV = '';
      //This condition will generate the Label/Header
      if (ShowLabel) {
          var row = "";

          //This loop will extract the label from 1st index of on array
          for (var index in arrData[0]) {
              //Now convert each value to string and comma-seprated
              row += index.trim().toUpperCase() + ',';
          }
          row = row.slice(0, -1);
          //append Label row with line break
          CSV += row + '\r\n';
      }

      //1st loop is to extract each row
      for (var i = 0; i < arrData.length; i++) {
          var row = "";
          //2nd loop will extract each column and convert it in string comma-seprated
          for (var index in arrData[i]) {
            var entry = arrData[i][index];
            var el = entry;
            if (index == "contact") {
              // assignedAgent
              el = entry["name"];             
            }  
            if (index == "assignedAgent") {
              // assignedAgent
              el = entry["name"] + " ( " + entry["email"] + " )";             
            }            
            row += '"' + el + '",';
          }
          row.slice(0, row.length - 1);
          //add a line break after each row
          CSV += row + '\r\n';
      }
      return CSV;
    },
    downloadCSATReports() {
      const fileName = `csat-report-${this.currentTime()}.csv`;
      // var csv = [];
      // csv[0] = ["CONTACT", "ASSIGNED AGENT", "RATING", "FEEDBACK COMMENT", "CONVERSATION ID"];
      var rows = this.JSONToCSVConvertor(this.tableData, true);
      // console.log(rows)
      downloadCsvFile(fileName, rows);
    },
  },
};
</script>
<style lang="scss" scoped>
.csat--table-container {
  display: flex;
  flex-direction: column;
  flex: 1;

  .ve-table {
    background: var(--white);

    &::v-deep {
      .ve-table-container {
        border-radius: var(--border-radius-normal);
        border: 1px solid var(--color-border) !important;
      }

      th.ve-table-header-th {
        font-size: var(--font-size-mini) !important;
        padding: var(--space-normal) !important;
      }

      td.ve-table-body-td {
        padding: var(--space-small) var(--space-normal) !important;
      }
    }
  }

  &::v-deep .ve-pagination {
    background-color: transparent;
  }

  &::v-deep .ve-pagination-select {
    display: none;
  }

  .emoji-response {
    font-size: var(--font-size-large);
  }

  .table-pagination {
    margin-top: var(--space-normal);
    text-align: right;
  }
}

.csat--empty-records {
  align-items: center;
  background-color: var(--white);
  border: 1px solid var(--color-border);
  border-top: 0;
  color: var(--b-600);
  display: flex;
  font-size: var(--font-size-small);
  height: 20rem;
  justify-content: center;
  margin-top: -1px;
  width: 100%;
}

.csat--timestamp {
  color: var(--b-400);
  font-size: var(--font-size-small);
}
</style>



```

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/issues/3662

**Comment by sojan-official** [comment]
Closing this since we don't track epics on github anymore, rather via individual issues.
