### ISSUE TITLE
epic: Swagger Documentation

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3583]
# Tasks
- [ ] Identify the missing attributes available for the contacts model ( example bio,company etc.) ( update widget, application, public apis)
- [x] https://github.com/chatwoot/chatwoot/issues/3599
- [x] https://github.com/chatwoot/chatwoot/issues/3962
- [x] Agent EndPoint
- [x] Team Members Endpoint : https://github.com/chatwoot/chatwoot/pull/4390
- [x] #4395
- [ ] #4396
- [x] #4327
- [x] https://github.com/chatwoot/chatwoot/issues/4466
