### ISSUE TITLE
feat: Fully configured Chatwoot Installation

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3586]
At the moment, after performing the installation the user has to manually configure SMTP server credentials for the agent emails to work.  Can we avoid the reliance on third-party providers and have chatwoot use a preconfigured SMTP server which the Linux installation script installs.  

## Tasks 
- [ ] Improve documentation for Email channels using postfix :  https://github.com/chatwoot/docs/issues/175 
- [x] #3696
- [ ] Explore if the same is possible for Heroku, caprover etc ( include a provider into build pack or add instructions )
- [ ] See if a mail server like postfix can be installed along with the Linux install script

**Comment by vishnu-narayanan** [comment]
@sojan-official I don't have a strong opinion on this one. Can be done either way. IMO most of the users would be using an external provider and coming to AWS, SES would be the defacto standard.

**Comment by sojan-official** [comment]
@vishnu-narayanan the motivation primarily comes from 
- the number of support queries in chatwoot related agent invite or password emails missing
- WordPress, GitLab etc comes packed with a native mechanism to send account emails like password resets 

We could in future expand the interface into something similar to wp email 
![wpsmtp2-708x516](https://user-images.githubusercontent.com/73185/146218271-9644d5fc-d887-4f98-a361-6f5eb6743a45.jpeg)

**Comment by vishnu-narayanan** [comment]
True the experience would be much better if we could bundle one together.

**Comment by pranavrajs** [comment]
@sojan-official I would consider AWS marketplace listing as a higher priority than this one. It improves the visibility of the product, helps me to navigate people directly to marketplace listing when making sales calls. 

Let us pick this one up next sprint. Meanwhile, if @nithindavid or @sojan-official can provide the expected UX flow, that would make things easier.

**Comment by vishnu-narayanan** [comment]
Related issue: https://github.com/chatwoot/charts/issues/18

**Comment by pranavrajs** [comment]
Closing due to lack of activity.
