### ISSUE TITLE
epic: Slack integration Improvements

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#4241]
- [ ] https://github.com/chatwoot/product/issues/632
- [x] #5767
- [ ] https://github.com/chatwoot/chatwoot/issues/1887
- [x] https://github.com/chatwoot/chatwoot/issues/1590
- [x] https://github.com/chatwoot/chatwoot/issues/1487
- [ ] https://github.com/chatwoot/chatwoot/issues/1488
- [ ] https://github.com/chatwoot/chatwoot/issues/4282
- [ ] https://github.com/chatwoot/chatwoot/issues/4339
- [x] https://github.com/chatwoot/product/issues/389
- [ ] https://github.com/chatwoot/product/issues/388
- [ ] https://github.com/chatwoot/product/issues/387
- [ ] https://github.com/chatwoot/product/issues/386
- [ ] https://github.com/chatwoot/product/issues/385
- [ ] https://github.com/chatwoot/chatwoot/issues/4397
- [ ] https://github.com/chatwoot/chatwoot/issues/4690
- [ ] https://github.com/chatwoot/chatwoot/issues/4729
- [ ] https://github.com/chatwoot/product/issues/631

**Comment by pranavrajs** [comment]
Closing this issue in favor of https://github.com/orgs/chatwoot/projects/31/views/2
