### ISSUE TITLE
epic: Chatwoot community edition(CE/FOSS) and enterprise edition(EE)

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#4268]
**Is your feature request related to a problem? Please describe.**

We introduced the `enterprise` folder and dual licensing with https://github.com/chatwoot/chatwoot/pull/3209. The `enterprise` folder can be removed to have a fully MIT compliant version. Make it easy to run fully open-source software.

**Describe the solution you'd like**
Start publishing both CE and EE editions when cutting a release with the CE version stripped of all proprietary code.
- [ ] Chatwoot FOSS repo
- [ ] Chatwoot EE and CE release artifacts
- [x] Chatwoot EE and CE docker images

## Todo
- [x] #4341
- [x] #4388
- [ ] Modify Linux installation script to support CE installation

**Describe alternatives you've considered**
Use the existing repo to create both CE and EE releases. No separate FOSS repo. 

**Additional context**
Similar to Gitlab and PostHog release model.

**Comment by vishnu-narayanan** [comment]
Single Repo approach
----

The current repo `chatwoot/chatwoot` serves as the source of truth.  All development and discussions happen over this repo. There will not be a separate `chatwoot-foss` repo.

### Creating release artifacts

When cutting a release, we could have an automated GitHub action that could strip the `/enterprise` folder and create a `ce` artifact along with `ee`. This can be accomplished by creating a separate `ce` tag.

For example,
https://github.com/chatwoot/chatwoot/archive/refs/tags/v2.3.2.tar.gz
https://github.com/chatwoot/chatwoot/archive/refs/tags/v2.3.2-ce.tar.gz

### Creating docker images
This can be accomplished via an additional docker file for CE edition which we can use to build the CE docker images at dockerhub. 

The tags can be v2.3.2-ce, latest-ce etc.

The docker pull would look like `docker pull chatwoot/chatwoot:latest-ce`.


### Advantages
- No two separate repos to maintain and keep in sync.
- Forks/stars/downloads and all other metrics  at one location.
- Docker metrics also across one repository

### Disadvanatages
- There won't be a fully MIT repo to clone easily.
- Release process with two repos would provide a clear separation between the releases. Tags can remain same across both versions.
   https://github.com/chatwoot/chatwoot-foss/archive/refs/tags/v2.3.2.tar.gz
   `docker pull chatwoot/chatwoot-foss:latest`

**Comment by vishnu-narayanan** [comment]
Multi Repo Approach
----
The current repo chatwoot/chatwoot serves as the canonical source of truth. All development and discussions happen over this repo. There will be a separate chatwoot-foss repo which will be stripped of all proprietary code and fully MIT.

### How?
`master`, `develop` and other release branches would be kept in sync with `chatwoot-foss` repo. Feature branches can be skipped. Also, the `tags` should be kept in sync.

This would be tedious and error-prone to do manually. Probably an automated way via a GitHub action.

### Advantages
- Fully MIT licensed repo of Chatwoot will be available for everyone.
- Existing release process would be sufficient to generate both versions. 
- Tags can be the same across both releases. Users should be able to just change the repo name to get the EE or CE version.


### Disadvantages
- Need to have an automated way to keep both repos in sync.
- Forks/stars/downloads and all other metrics at one location.
- Docker metrics will also be spread across two repositories.
-

**Comment by vishnu-narayanan** [comment]
- [ ] Run ci tests against foss codebase for every PR (strip enterprise folder and spec)
- [ ] Run gh action to generate a docker image for CE edition
- [ ] Modify Linux installation script to support CE installation

**Comment by pranavrajs** [comment]
@vishnu-narayanan Sounds good

**Comment by pranavrajs** [comment]
Closing this as the docker builds are complete and omnibus installation would be tracked over https://github.com/chatwoot/product/issues/204
