### ISSUE TITLE
epic: Dialogflow Integration Improvements

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#4276]
Tracking the issues and feature requests related to dialogflow 

- [ ] https://github.com/chatwoot/chatwoot/issues/4271
- [ ] https://github.com/chatwoot/chatwoot/issues/4129
- [x] https://github.com/chatwoot/chatwoot/issues/4004
- [ ] https://github.com/chatwoot/chatwoot/issues/3883 : Ability to add custom attributes from dialogflow
- [ ] https://github.com/chatwoot/chatwoot/issues/3910
- [ ] https://github.com/chatwoot/chatwoot/issues/3759
- [ ] https://github.com/chatwoot/chatwoot/issues/3071
- [ ] https://github.com/chatwoot/chatwoot/issues/2994
- [ ] https://github.com/chatwoot/chatwoot/issues/2993
- [ ] https://github.com/chatwoot/chatwoot/issues/2383
- [ ] #4745

**Comment by SebastianBitsch** [comment]
Hi, @sojan-official any updates on this?

**Comment by pranavrajs** [comment]
Closing this as we will track the progress here. https://github.com/orgs/chatwoot/projects/31/views/3
