### ISSUE TITLE
epic: Line Channel

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#4343]
Tracking issues related to line channel

- [ ] https://github.com/chatwoot/chatwoot/issues/4073
- [ ] https://github.com/chatwoot/chatwoot/issues/3920
- [ ] https://github.com/chatwoot/chatwoot/issues/3038
