### ISSUE TITLE
epic: Email Channel

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#4345]
## Issues 
- [x] https://github.com/chatwoot/chatwoot/issues/4315
- [x] https://github.com/chatwoot/chatwoot/issues/4311
- [x] https://github.com/chatwoot/chatwoot/issues/4218
- [x] https://github.com/chatwoot/chatwoot/issues/4166
- [x] https://github.com/chatwoot/chatwoot/issues/4151
- [x] https://github.com/chatwoot/chatwoot/issues/4130
- [x] https://github.com/chatwoot/chatwoot/issues/4094
- [x] https://github.com/chatwoot/chatwoot/issues/4118
- [x] https://github.com/chatwoot/chatwoot/issues/4056
- [ ] https://github.com/chatwoot/chatwoot/issues/4007
- [x] https://github.com/chatwoot/chatwoot/issues/3996
- [x] https://github.com/chatwoot/chatwoot/issues/4001
- [x] https://github.com/chatwoot/chatwoot/issues/3954
- [ ] https://github.com/chatwoot/chatwoot/issues/3891
- [x] https://github.com/chatwoot/chatwoot/issues/3869
- [x] https://github.com/chatwoot/chatwoot/issues/3868
- [x] https://github.com/chatwoot/chatwoot/issues/3720
- [x] https://github.com/chatwoot/chatwoot/issues/3572
- [x] https://github.com/chatwoot/chatwoot/issues/3544
- [x] https://github.com/chatwoot/chatwoot/issues/3606
- [x] https://github.com/chatwoot/chatwoot/issues/3388
- [ ] https://github.com/chatwoot/chatwoot/issues/3379
- [ ] https://github.com/chatwoot/chatwoot/issues/3240
- [ ] https://github.com/chatwoot/chatwoot/issues/3006
- [x] https://github.com/chatwoot/chatwoot/issues/2712
- [x] https://github.com/chatwoot/chatwoot/issues/2690
- [x] https://github.com/chatwoot/chatwoot/issues/2660
- [x] https://github.com/chatwoot/chatwoot/issues/2006
- [ ] https://github.com/chatwoot/chatwoot/issues/1959
- [x] https://github.com/chatwoot/chatwoot/issues/1692
- [ ] https://github.com/chatwoot/chatwoot/issues/1074
- [ ] https://github.com/chatwoot/chatwoot/issues/980
- [x] https://github.com/chatwoot/chatwoot/issues/1063
- [x] https://github.com/chatwoot/chatwoot/issues/4381
- [ ] https://github.com/chatwoot/product/issues/402
- [x] https://github.com/chatwoot/chatwoot/issues/4532
- [x] https://github.com/chatwoot/chatwoot/issues/4634
- [ ] https://github.com/chatwoot/chatwoot/issues/4629
- [ ] https://github.com/chatwoot/chatwoot/issues/4746
- [x] https://github.com/chatwoot/chatwoot/issues/4646

**Comment by sojan-official** [comment]
Closing this since we don't track epics on github anymore, rather via individual issues.
