### ISSUE TITLE
epic: Agent Productivity

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#4349]
## Issues

- [x] https://github.com/chatwoot/chatwoot/issues/3550
- [ ] https://github.com/chatwoot/chatwoot/issues/4346
- [x] https://github.com/chatwoot/chatwoot/issues/3972
- [x] https://github.com/chatwoot/chatwoot/issues/4264
- [ ] https://github.com/chatwoot/chatwoot/issues/4590
- [ ] https://github.com/chatwoot/chatwoot/issues/2710
- [x] https://github.com/chatwoot/chatwoot/issues/2983
- [x] https://github.com/chatwoot/chatwoot/issues/1546
- [ ] https://github.com/chatwoot/chatwoot/issues/4528
- [x] #4780
- [x] https://github.com/chatwoot/chatwoot/issues/4779

**Comment by pranavrajs** [comment]
Closing this here as it is a placeholder ticket.
