### ISSUE TITLE
epic: Conversation Enhancements 

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#4353]
## Issues

- [ ] https://github.com/chatwoot/chatwoot/issues/3627
- [ ] https://github.com/chatwoot/chatwoot/issues/3277
- [x] https://github.com/chatwoot/chatwoot/issues/2587
- [x] https://github.com/chatwoot/chatwoot/issues/2099
- [x] https://github.com/chatwoot/chatwoot/issues/1021
- [ ] https://github.com/chatwoot/chatwoot/issues/1632
- [ ] https://github.com/chatwoot/chatwoot/issues/1109
- [ ] https://github.com/chatwoot/chatwoot/issues/3398
- [ ] https://github.com/chatwoot/chatwoot/issues/4047
- [x] https://github.com/chatwoot/chatwoot/issues/4646
- [x] https://github.com/chatwoot/chatwoot/issues/4634
- [ ] https://github.com/chatwoot/chatwoot/issues/4526

**Comment by duongvanphung** [comment]
i need #1137

**Comment by sojan-official** [comment]
Closing this since we don't track epics on github anymore, rather via individual issues.
