### ISSUE TITLE
epic: Error Tracking & Logging 

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4374]
- [ ] Standardize the logging framework in Chatwoot, create a common class for logs, and mask PII.
- [x] https://github.com/chatwoot/docs/issues/252
- [x] https://github.com/chatwoot/product/issues/367
- [ ] https://github.com/chatwoot/chatwoot/issues/4371
- [x] #4375
- [x] https://github.com/chatwoot/chatwoot/issues/4592
- [x] https://github.com/chatwoot/chatwoot/issues/4138

**Comment by pranavrajs** [comment]
Closing due to lack of activity.
