### ISSUE TITLE
epic: Campaigns

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#4379]
# Issues

- [ ] https://github.com/chatwoot/chatwoot/issues/4201
- [ ] https://github.com/chatwoot/chatwoot/issues/4097
- [ ] https://github.com/chatwoot/chatwoot/issues/4026
- [ ] https://github.com/chatwoot/chatwoot/issues/3997
- [ ] https://github.com/chatwoot/chatwoot/issues/3624
- [x] https://github.com/chatwoot/chatwoot/issues/3574
- [ ] https://github.com/chatwoot/chatwoot/issues/3363
- [ ] https://github.com/chatwoot/chatwoot/issues/3192
- [ ] https://github.com/chatwoot/chatwoot/issues/3124
- [ ] https://github.com/chatwoot/chatwoot/issues/2768
- [x] https://github.com/chatwoot/chatwoot/issues/2739
- [ ] https://github.com/chatwoot/chatwoot/issues/2434
- [ ] https://github.com/chatwoot/chatwoot/issues/2431
- [ ] https://github.com/chatwoot/chatwoot/issues/2334
- [ ] https://github.com/chatwoot/chatwoot/issues/2287
- [ ] https://github.com/chatwoot/chatwoot/issues/2282
- [ ] #4380
- [ ] #4426
- [ ] https://github.com/chatwoot/chatwoot/issues/4527
- [ ] https://github.com/chatwoot/chatwoot/issues/4531
- [ ] https://github.com/chatwoot/chatwoot/issues/4379
