### ISSUE TITLE
Epic: Widget Improvements

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#4424]
## Issues 

- [ ] https://github.com/chatwoot/chatwoot/issues/3329
- [ ] https://github.com/chatwoot/chatwoot/issues/4335
- [ ] https://github.com/chatwoot/chatwoot/issues/4299
- [ ] https://github.com/chatwoot/chatwoot/issues/4289
- [ ] https://github.com/chatwoot/chatwoot/issues/4287
- [ ] https://github.com/chatwoot/chatwoot/issues/4233
- [ ] https://github.com/chatwoot/chatwoot/issues/4026
- [ ] https://github.com/chatwoot/chatwoot/issues/3856
- [ ] https://github.com/chatwoot/chatwoot/issues/3816
- [ ] https://github.com/chatwoot/chatwoot/issues/3789
- [ ] https://github.com/chatwoot/chatwoot/issues/3789
- [ ] https://github.com/chatwoot/chatwoot/issues/3624
- [ ] https://github.com/chatwoot/chatwoot/issues/3424
- [ ] https://github.com/chatwoot/chatwoot/issues/3347
- [ ] https://github.com/chatwoot/chatwoot/issues/3373
- [ ] https://github.com/chatwoot/chatwoot/issues/3141
- [ ] https://github.com/chatwoot/chatwoot/issues/3191
- [ ] https://github.com/chatwoot/chatwoot/issues/3182
- [ ] https://github.com/chatwoot/chatwoot/issues/2998
- [ ] https://github.com/chatwoot/chatwoot/issues/2995
- [ ] https://github.com/chatwoot/chatwoot/issues/2914
- [ ] https://github.com/chatwoot/chatwoot/issues/2913
- [ ] https://github.com/chatwoot/chatwoot/issues/2910
- [ ] https://github.com/chatwoot/chatwoot/issues/2909
- [ ] https://github.com/chatwoot/chatwoot/issues/2879
- [ ] https://github.com/chatwoot/chatwoot/issues/2859
- [ ] https://github.com/chatwoot/chatwoot/issues/2858
- [ ] https://github.com/chatwoot/chatwoot/issues/2852
- [ ] https://github.com/chatwoot/chatwoot/issues/2811
- [ ] https://github.com/chatwoot/chatwoot/issues/2745
- [ ] https://github.com/chatwoot/chatwoot/issues/2744
- [ ] https://github.com/chatwoot/chatwoot/issues/2441
- [ ] https://github.com/chatwoot/chatwoot/issues/2431
- [ ] https://github.com/chatwoot/chatwoot/issues/2355
- [ ] https://github.com/chatwoot/chatwoot/issues/2099
- [ ] https://github.com/chatwoot/chatwoot/issues/1237
- [ ] https://github.com/chatwoot/chatwoot/issues/1121
- [ ] https://github.com/chatwoot/chatwoot/issues/1231
- [ ] https://github.com/chatwoot/chatwoot/issues/1109
- [ ] https://github.com/chatwoot/chatwoot/issues/1100
- [ ] https://github.com/chatwoot/chatwoot/issues/595
- [ ] https://github.com/chatwoot/chatwoot/issues/320
- [ ] https://github.com/chatwoot/chatwoot/issues/273
- [ ] https://github.com/chatwoot/chatwoot/issues/714
- [ ] https://github.com/chatwoot/chatwoot/issues/2745

**Comment by iammattmartin** [comment]
#3789 is not fixed and still an issue.

**Comment by sojan-official** [comment]
Closing this since we don't track epics on github anymore, rather via individual issues.
