### ISSUE TITLE
epic: Automations

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#4478]
Tracking various community requests related to automation 

- [ ] https://github.com/chatwoot/chatwoot/issues/4433
- [x] https://github.com/chatwoot/chatwoot/issues/4459
- [x] https://github.com/chatwoot/chatwoot/issues/3951
- [ ] https://github.com/chatwoot/chatwoot/issues/4542
- [x] https://github.com/chatwoot/chatwoot/issues/4590
- [x] https://github.com/chatwoot/chatwoot/issues/4717
- [x] https://github.com/chatwoot/chatwoot/issues/4806

**Comment by sojan-official** [comment]
Closing this since we don't track epics on github anymore, rather via individual issues.
