### ISSUE TITLE
epic: Whatsapp Channel

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#4512]
Epic Tracking the Whatsapp Related Tickets in Chatwoot

## Bugs
- [x] https://github.com/chatwoot/chatwoot/issues/4481
- [ ] https://github.com/chatwoot/chatwoot/issues/4468
- [x] https://github.com/chatwoot/chatwoot/issues/3850
- [x] #5078
- [x] https://github.com/chatwoot/chatwoot/issues/5128
- [x] https://github.com/chatwoot/chatwoot/issues/4995
- [x] https://github.com/chatwoot/chatwoot/issues/3643
- [x] https://github.com/chatwoot/chatwoot/issues/3632
- [ ] https://github.com/chatwoot/chatwoot/issues/5367

## Enhancements
- [x] https://github.com/chatwoot/chatwoot/issues/4975
- [x] https://github.com/chatwoot/chatwoot/issues/3772

## Features
- [x] https://github.com/chatwoot/chatwoot/issues/4201
- [ ] https://github.com/chatwoot/chatwoot/issues/4146
- [ ] https://github.com/chatwoot/chatwoot/issues/3627
- [ ] https://github.com/chatwoot/chatwoot/issues/3398
- [x] https://github.com/chatwoot/chatwoot/issues/1021
- [ ] https://github.com/chatwoot/chatwoot/issues/2641
- [x] https://github.com/chatwoot/chatwoot/issues/2691
- [x] https://github.com/chatwoot/chatwoot/issues/4917
- [x] #4712
- [x] https://github.com/chatwoot/chatwoot/issues/1020
- [x] https://github.com/chatwoot/chatwoot/issues/2099
- [x] https://github.com/chatwoot/chatwoot/issues/3538

**Comment by sanjayws** [comment]
Pls add location support too 😅

**Comment by juanfrancisco-18** [comment]
el desarrollo está  muy complicado?

**Comment by digitall-it** [comment]
6 over 18! Go go, Power Rangers!

**Comment by sojan-official** [comment]
Closing this since we don't track epics on github anymore, rather via individual issues.
