### ISSUE TITLE
epic: Interactive messages

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#4636]
Goal: A unified API for interactive messages in Chatwoot, which would be translated accordingly into the implementation of the underlying channel. 

## issues
- [ ] https://github.com/chatwoot/chatwoot/issues/4541
- [x] https://github.com/chatwoot/chatwoot/issues/4527
- [x] https://github.com/chatwoot/chatwoot/issues/3538
- [ ] https://github.com/chatwoot/chatwoot/issues/4589
- [ ] https://github.com/chatwoot/chatwoot/issues/4736

**Comment by rmundel** [comment]
Also Add Twilio Wpp buttons would be nice
https://www.twilio.com/blog/using-whatsapp-quick-reply-buttons-for-more-engaging-customer-experiences

**Comment by sojan-official** [comment]
@rmundel  You should be able t send the buttons even now.  You can get a button template approved on Twilio, add the body text as a canned response in chatwoot and send the same message body from chatwoot so that  the template message will be rendered on the WhatsApp end

ref: https://www.twilio.com/docs/whatsapp/buttons#sending-templates-with-buttons

**Comment by sojan-official** [comment]
Closing this since we don't track epics on github anymore, rather via individual issues.
