### ISSUE TITLE
epic: Super Admin

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#4715]
## Issues
- [x] https://github.com/chatwoot/chatwoot/issues/4714
- [x] https://github.com/chatwoot/chatwoot/issues/4611
- [x] https://github.com/chatwoot/chatwoot/issues/4455
- [x] https://github.com/chatwoot/chatwoot/issues/4164
- [x] https://github.com/chatwoot/chatwoot/issues/1590
- [x] https://github.com/chatwoot/chatwoot/issues/1125
- [ ] https://github.com/chatwoot/chatwoot/issues/1101
- [x] https://github.com/chatwoot/chatwoot/issues/1027
