### ISSUE TITLE
epic: Website Channel

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#4730]
## Issues

- [x] #4731
- [x] https://github.com/chatwoot/chatwoot/issues/4320
- [ ] https://github.com/chatwoot/chatwoot/issues/4728
- [x] https://github.com/chatwoot/chatwoot/issues/2811
- [x] https://github.com/chatwoot/chatwoot/issues/4735
- [ ] #4740

**Comment by sojan-official** [comment]
Closing this since we don't track epics on github anymore, rather via individual issues.
