### ISSUE TITLE
Recreate index in custom_attribute_definitions table

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4891]
Some of the self-hosted installations seem to have invalid indexes on custom attribute definitions. (The index attribute_model, attribute_key exists, possibly due to the existing migrations didn't work properly). 

**Todo:** 
- [ ] Remove all indexes on table
- [ ] Add index on account_id
- [ ] Add a unique index on (attribute_model, attribute_key, account_id)

**Comment by pranavrajs** [comment]
Closing due to lack of activity.
