### ISSUE TITLE
feat: Retain only a single conversation thread for channels like WhatsApp / SMS 

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#4975]
ref: https://github.com/chatwoot/chatwoot/pull/4906 

Currently, the new conversation option in the contacts panel creates a whole new conversation for Channels like SMS & Whatsapp. Should We append it to the same thread if an existing conversation exists rather than creating a new conversation thread as the underlying Channels are only retaining a single conversation thread?

Before building further integrations, we must also confirm the intended behavior for other similar channels.

> note: Since the existing behavior for SMS and WhatsApp channel allows the creation of new conversations, there could be integrations built over this assumption; we will also need to assess the impact of this change before proceeding. 

Impacted Channels

- Messenger
- Twitter DM 
- Whatsapp
- SMS 
- Line
- Telegram

------

### Case 1: Retain a single conversation thread 
- Replace the wording in the New conversation Dialog box with `New Message` when the conversation exists
- Append messages in the box to the existing thread instead of creating a new one. 
- How to handle resolution events, CSAT, etc.

### Case 2: Ability to create multiple threads

- The current behavior for Whatsapp & SMS inboxes
- As a further enhancement, probably need options in the system to create new conversations when messages arrive on existing resolved conversations
- The behavior mimics a ticketing system with individual issues considered a ticket with specific agent assignment, CSAT responses, etc.
- If there are multiple conversations against the same contact, the only option will be to append messages to the last conversation as it will be harder to determine the underlying ticket. [con]

### Case 3: Support Both 
- Configuration in the Inbox, which allows locking to a single thread: When this configuration is enabled, the system behaves like Case 1

### Other notes
- Impact on campaigns
- Impact on API calls
  
------

## TODOs

- [ ] Investigate & document the Pros & Cons of both the approaches
  - [ ]  Refer to existing products and make a note of various implementations
  - [ ]  Refer to customer forums to understand various requirements
  - [ ] Figure out a conclusion and create associate tickets

**Comment by iammattmartin** [comment]
On new, maybe but for existing, that should be optional. i.e if conversation is resolved, some may want any new messages to appear as a new conversation.

Maybe the option to merge to a previous convo of the same channel would be useful!

**Comment by hugodeco** [comment]
For now, would be great if we can search for an "NOT CLOSED" conversations via API.
Today we have to retrieve all conversations of an specific client and than filter a "NOT CLOSED" status to post the new message.
As "NOT CLOSED" means all status code that not means a resolution for a conversation, like "delayed,pending,open" ....

**Comment by sojan-official** [comment]
# Changes to implement 

- Enable toggle for channels that requires control for threads, i.e., Channels that only support a single conversation thread. [ Lock to Single conversation ]
    - Messenger
    - Twitter DM
    - SMS
    - Whatsapp
    - Telegram
    -  Line
 
 -  When Lock to Single conversation is enabled in a channel
    - When creating an outbound conversation to a contact with an existing conversation, Change the copy to `Send a new message` instead of `Create new conversation.`
