### ISSUE TITLE
epic: self-hosted docker enhancements

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#5170]
- [x] improve the overall installation experience
- [x] https://github.com/chatwoot/docs/issues/263
- [x] https://github.com/chatwoot/chatwoot/issues/4894
- [x] https://github.com/chatwoot/chatwoot/issues/4278
- [x] https://github.com/chatwoot/chatwoot/issues/3407
- [ ] explore docker swarm support
- [ ] explore portainer support

**Comment by vishnu-narayanan** [comment]
Closing this. Pending tasks has equivalent tickets in linear.
