### ISSUE TITLE
Mark WhatsApp Cloud API as active after successful webhook verification

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#5298]
> When we paste the webhook URL and the token on the Facebook dev portal, is there a way for Chatwoot to know that the URL and token have been pasted successfully? This will help us inform the user that the inbox is ready.

**Todo:**
- [ ] Check if we can mark an Inbox as active (Update the UI to add this indicator)
- [ ] Can we use the Facebook Callback to confirm the inbox as active?

**Comment by sojan-official** [comment]
### Notes
- [ ] Introduce an attribute to the inbox marking whether it's active
- [ ] Mark the attribute active when a successful Websocketevent is received from the external channel [ Facebook, Instagram, Whatsapp, Line, Telegram, etc.]
- [ ] Modify the Inbox creation last step to redirect the user to the newly created inbox only after it has been marked as active. Provide further faq on if the activation is taking time. Choose either of the following events
       1. Poll the inbox API and show the inbox is ready to use message only when it gets marked as active
        2. https://github.com/chatwoot/chatwoot/issues/5348

cc: @pranavrajs
