### ISSUE TITLE
Integrate Retool with Chatwoot

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#5692]
**Context**: https://discord.com/channels/647412545203994635/1006470116432695368/threads/1032259204578279434

<img width="780" alt="Screenshot 2022-10-20 at 5 47 49 PM" src="https://user-images.githubusercontent.com/2246121/197085893-ebf6d661-3bb8-4b18-aab0-88b06a81d638.png">

**Investigation Results:**

The Retool app runs in a sandbox so the direct postMessage option doesn't work. We would have to integrate their SDK inside Chatwoot to communicate with the app.

React - Retool SDK: https://github.com/tryretool/react-retool

**Todo:** 

- [ ] Port Retool React SDK to Vue
- [ ] Use `vue-retool` component as a new type along with the iframe type in the dashboard app
- [ ] Add a dropdown in the dashboard to select between an iframe and a Retool app.

**Comment by brundles** [comment]
This could be "nice" - but seems like something that could wait. How large of the userbase do you estimate use Retool?
