### ISSUE TITLE
Macros - Release v1

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#5730]
Macros CRUD operations and execution is completed already. During the test, we found a couple of improvements/bugs. The list is added below.

#### Permissions:
- [x] Agents can update/delete their own macros.
- [x] Any agent or admin can only delete the macros they created or orphan macros (any macros created by an agent who was previously a part of the team).
- [x] A public macro created by one agent should be available in read-only mode to other agents, it should not be editable. Admins can edit it.
- [x] Admin can change the visibility of all the macros.
- [x] Order macros by ID. (Let us move it to last used later on)

#### UI Update for the permissions

- [ ] If agents/admins are changing a public macro to private, alert them that “You are changing the visibility of the macro. This action would make it private and it would be only available to the agent who created it”. Once confirmed, update the macro.

#### Chores
- [x] Make sure that the macros created_by / edited_by become `null` if an agent is removed from the account.
- [ ] Rename the visibility in the code to public/private instead of global/personal in the code and external facing APIs.

#### New

- [x] #5733
- [x] #5735
- [x] #5736
- [x] #5734

### Bugs

- [x] #5731
- [x] #5732

**Comment by nithindavid** [comment]
@pranavrajs Can we have canned response support for macros? 
This can be solved alternatively by having rich text editor there(With toggle option to support other channels)

**Comment by tejaswinichile** [comment]
@nithindavid "Send Canned response" something like this? And the save the content for canned responses?

**Comment by fayazara** [comment]
> @nithindavid "Send Canned response" something like this? And the save the content for canned responses?

@tejaswinichile We already have the `send message` option, right.

**Comment by tejaswinichile** [comment]
@fayazara We would need at least a short code to be saved right, for canned responses?

**Comment by tejaswinichile** [comment]
> Make sure that the macros created_by / edited_by become null if an agent is removed from the account.

This is valid for only public macros created by an agent, as we are deleting the private Macros.

**Comment by pranavrajs** [comment]
Closing due to lack of activity.
