### ISSUE TITLE
Message templates 

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#5894]
### **Problem**

We have canned responses which are saved reply templates that are used to send out a reply to a conversation quickly. The agents can use canned responses to save replies to frequently asked questions, which will help reduce an agent's response time and productivity. An agent can access canned responses while chatting by typing **`/`**followed by the shortcode.

But the current approach has some issues.

- Unable to add variables. For ex: Add a {{userName}} kind of variable in canned responses, so that they can feel personalised for the end user.
- There is no support for message templates in macros/automation. eg: To send a message to a customer, if we support templates like " Hey {{name}}, how are you?", which would create a better experience for the customer.

### Solution

- Use rich content editor in canned responses.
- Add the support for variables in canned responses.
- Add fall back text for variables ex: Hey {{ contact.firstName || `there`}}
- Highlight the variables in the editor.
- Add the ability to add message templates anywhere in the message box (ReplyBox/Macros/Automation/Conversation from contact).

### Design Mocks

![Screenshot 2022-11-17 at 3 05 09 PM](https://user-images.githubusercontent.com/12408980/202413395-48c22bb2-fe10-46d6-9537-1216f8505477.png)
![Screenshot 2022-11-17 at 3 12 09 PM](https://user-images.githubusercontent.com/12408980/202413428-0973a004-6564-4187-bc11-10c49793d2e6.png)

## Questions

- Should we standardize the editor ([https://github.com/chatwoot/chatwoot/issues/2659](https://github.com/chatwoot/chatwoot/issues/2659)) ?
- Should we use message templates instead of canned responses?
- How to handle default user names?

### Related Issues

- [https://github.com/chatwoot/chatwoot/issues/2084](https://github.com/chatwoot/chatwoot/issues/2084)
- [https://github.com/chatwoot/chatwoot/issues/1886](https://github.com/chatwoot/chatwoot/issues/1886)

### Tasks

- [x] #6078
- [x] https://github.com/chatwoot/chatwoot/pull/6077
- [x] https://github.com/chatwoot/chatwoot/issues/6259
- [x] https://github.com/chatwoot/chatwoot/issues/6260

**Comment by pranavrajs** [comment]
@muhsin-k Thanks for compiling this. The solution looks good. 

> Should we standardize the editor?

This needs an investigation plain text output is required for all the channels except the website and email. The prose-mirror editor doesn't have the support for it. @nithindavid might be able to add a new schema to output non-markdown results.

> Should we use message templates instead of canned responses?

I'm not sure if I understand this properly. I believe Canned Response and Message templates should not be different rather template option is an add to canned responses. Support for templates should be common, but it doesn't need to be saved separately.

> How to handle default user names?

We should only populate names if the contact is resolved (have an email/phone/identifier). Otherwise, it should create messages like `Hey random-name-243`

**Comment by muhsin-k** [comment]
- [ ] Support variables in the message content

**Comment by yagoalon** [comment]
Is this working?

How should i enable it? I have updated to the last version, but variables are not working. 

thanks,

**Comment by muhsin-k** [comment]
@yagoalon Yes. You can use short codes like `{{ contact.name }}`  in messages, canned responses etc. Chatwoot will translate it to the appropriate value.
We support the following variables at the moment,
`conversation.id, contact.id, contact.name, contact.last_name, contact.email, contact.phone, agent.name, agent.first_name, agent.last_name and agent.email `
