### ISSUE TITLE
epic: Build FAQs into chatwoot ( knowledge base articles )

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#714]
**Is your feature request related to a problem? Please describe.**
Often the questions that come up in chatwoot are the same. Solve with via an FAQ option in chatwoot

**Describe the solution you'd like**
 if the agents can create FAQs that the user can search for in the chat widget. that will be great. 

## Tasks

- [ ]  feat: Crud API endpoints for articles
- [ ]  feat: Crud API endpoints for folders
- [ ] https://github.com/chatwoot/chatwoot/issues/4395

**Comment by aermike** [comment]
Try with Articulate
Link may be made with webhooks
https://github.com/samtecspg/articulate

**Comment by ChrisvanChip** [comment]
What discussion is required on this feature? Or, does it require discussion from the Chatwoot team?

**Comment by sojan-official** [comment]
@ChrisvanChip  Just requires prioritization from the team internally and evaluation of remaining effort.

**Comment by ETMitch21** [comment]
I would absolutely love to see a knowledge base implemented into Chatwoot. I feel like it's just about the only thing missing from this incredible software! I'm excited to know others feel the same way.

**Comment by ChrisvanChip** [comment]
> @ChrisvanChip Just requires prioritization from the team internally and evaluation of remaining effort.

Hi @sojan-official, is there an estimate on how long these priorizations will take? We're really looking forward to an integrated knowledgebase.

**Comment by pranavrajs** [comment]
@ChrisvanChip A product spec is in progress. You can expect the feature by the July release.

**Comment by pranavrajs** [comment]
Closing in favour of #4593
